name: ci
on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SHA12: $(git rev-parse --short HEAD)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Test
        run: echo $SHORT_SHA
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          push: true
#          tags: taras13/app:$(echo ${{ github.sha }} | head -c7)
#          build-args: |
#            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
